### PR TITLE
Fix/132 es6 modules

### LINKED ISSUE #132: Only use one JS module system
There's a weird mix of node.js and es6 module imports, we should have just one kind (I think).

### PR DESCRIPTION
**Pull request by AlexPikalov**
Fixes #132 

Also I've added few TODOs related to using ES6 features.

### CODE REVIEW

**Comment by nrc** [comment]
This is great, thank you!

**Comment by AlexPikalov** [comment]
NP, I'm glad to help.

**Comment by AlexPikalov** [comment]
@nrc Seems that I need to fix application bootstrap step. Sorry for that. Will create a PR.

**Comment by AlexPikalov** [comment]
#144

**Pull request merged**
